### ISSUE TITLE
[BUG]httpx.ReadTimeout: timed out

### ISSUE THREAD

**Issue by mayonggang** [issaccv/aiops24-RAG-demo#10]
### 检查之前的issues

- [X] 我已经检查过之前的issues，没有我遇到的问题

### 描述Bug

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/autodl-tmp/aiops24-RAG-demo/demo/main.py", line 81, in <module>
    asyncio.run(main())
  File "/root/miniconda3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/autodl-tmp/aiops24-RAG-demo/demo/main.py", line 71, in main
    result = await generation_with_knowledge_retrieval(
  File "/root/autodl-tmp/aiops24-RAG-demo/demo/pipeline/rag.py", line 82, in generation_with_knowledge_retrieval
    ret = await llm.acomplete(fmt_qa_prompt)
  File "/root/miniconda3/lib/python3.10/site-packages/llama_index/core/llms/callbacks.py", line 257, in wrapped_async_llm_predict
    f_return_val = await f(_self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/llama_index/core/llms/custom.py", line 68, in acomplete
    return self.complete(prompt, formatted=formatted, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/llama_index/core/llms/callbacks.py", line 323, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/llama_index/llms/ollama/base.py", line 181, in complete
    response = client.post(
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_client.py", line 1145, in post
    return self.request(
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/root/miniconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out

### 复现步骤

突然就这样了 在embedding完成之后 就会出现。

### 代码分支

main

### 运行环境

本地环境

**Comment by issaccv** [comment]
本地环境比较复杂哈，请提供更多详细的环境信息，方便进一步排查

从当前的信息看是因为回答生成的太慢了，在超时限制之前仍没有返回数据
