### ISSUE TITLE
httpx.ConnectError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by 871674389** [issaccv/aiops24-RAG-demo#11]
### 检查之前的issues

- [X] 我已经检查过之前的issues，没有我遇到的问题

### 描述Bug

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 357, in async_wrapper
    result = await func(*args, **kwargs)
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/llama_index/core/async_utils.py", line 117, in worker
    return await job
  File "/mnt/workspace/aiops24-RAG-demo/demo/dense_pack/llama_index/packs/dense_x_retrieval/base.py", line 138, in _aget_proposition
    inital_output = await self._proposition_llm.apredict(
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in async_wrapper
    result = await func(*args, **kwargs)
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/llama_index/core/llms/llm.py", line 515, in apredict
    chat_response = await self.achat(messages)
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/llama_index/core/llms/callbacks.py", line 71, in wrapped_async_llm_chat
    f_return_val = await f(_self, messages, **kwargs)
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/llama_index/core/llms/custom.py", line 49, in achat
    return self.chat(messages, **kwargs)
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/llama_index/core/llms/callbacks.py", line 144, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/llama_index/llms/ollama/base.py", line 101, in chat
    response = client.post(
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1145, in post
    return self.request(
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/mnt/workspace/aiops24-RAG-demo/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

### 复现步骤

运行main.py，请求与 Ollama 服务器通信时发生了连接拒绝错误

### 预期行为

运行结果

### 代码分支

main

### 运行环境

ModelScope（魔搭）

**Comment by issaccv** [comment]
请重新pull一下demo，这个是由于ollama的二进制文件没有执行权限，导致ollama并没有运行

已经在这个commit https://github.com/issaccv/aiops24-RAG-demo/commit/9254b542c1b85a2191e5806402e2c1478d35d4af 中解决了
