### ISSUE TITLE
换了个embedding model，出现了ValueError: could not broadcast input array from shape (1024,) into shape (512,)

### ISSUE THREAD

**Issue by yafangwang9** [issaccv/aiops24-RAG-demo#14]
### 检查之前的issues

- [X] 我已经检查过之前的issues，没有我遇到的问题

### 描述Bug

Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 42139/42139 [00:15<00:00, 2679.93it/s]
Generating embeddings: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 244/244 [15:27<00:00,  3.80s/it]
Traceback (most recent call last):
  File "/mnt/workspace/aiops24-RAG-demo/demo/main.py", line 74, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/mnt/workspace/aiops24-RAG-demo/demo/main.py", line 47, in main
    await pipeline.arun(documents=data, show_progress=True, num_workers=1)
  File "/usr/local/lib/python3.10/site-packages/llama_index/core/ingestion/pipeline.py", line 923, in arun
    await self.vector_store.async_add(
  File "/usr/local/lib/python3.10/site-packages/llama_index/vector_stores/qdrant/base.py", line 321, in async_add
    await self._aclient.upload_points(
  File "/usr/local/lib/python3.10/site-packages/qdrant_client/async_qdrant_client.py", line 1842, in upload_points
    return await self._client.upload_points(
  File "/usr/local/lib/python3.10/site-packages/qdrant_client/local/async_qdrant_local.py", line 672, in upload_points
    self._upload_points(collection_name, points)
  File "/usr/local/lib/python3.10/site-packages/qdrant_client/local/async_qdrant_local.py", line 683, in _upload_points
    collection.upsert(
  File "/usr/local/lib/python3.10/site-packages/qdrant_client/local/local_collection.py", line 1217, in upsert
    self._upsert_point(point)
  File "/usr/local/lib/python3.10/site-packages/qdrant_client/local/local_collection.py", line 1209, in _upsert_point
    self._add_point(point)
  File "/usr/local/lib/python3.10/site-packages/qdrant_client/local/local_collection.py", line 1151, in _add_point
    named_vectors[idx] = vector_np
ValueError: could not broadcast input array from shape (1024,) into shape (512,)

### 复现步骤

将embedding mode从bge-small-zh-v1.5换成了bge-large-zh-v1.5，出现了ValueError: could not broadcast input array from shape (1024,) into shape (512,)
运行main.py出现了报错
云服务器环境为：1x NVIDIA A10 24G 显存，30G 内存

### 代码分支

glm

### 运行环境

其他

**Comment by issaccv** [comment]
请检查.env文件，并根据嵌入模型的维度修改对应值
