### ISSUE TITLE
Error while deserializing header: HeaderTooLarge错误

### ISSUE THREAD

**Issue by kevind-sc** [issaccv/aiops24-RAG-demo#5]
### 检查之前的issues

- [X] 我已经检查过之前的issues，没有我遇到的问题

### 描述Bug

Traceback (most recent call last):
  File "/root/autodl-tmp/aiops24-RAG-demo/demo/main.py", line 71, in <module>
    asyncio.run(main())
  File "/root/miniconda3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/autodl-tmp/aiops24-RAG-demo/demo/main.py", line 22, in main
    embeding = HuggingFaceEmbedding(
  File "/root/autodl-tmp/aiops24-RAG-demo/demo/.venv/lib/python3.10/site-packages/llama_index/embeddings/huggingface/base.py", line 86, in __init__
    self._model = SentenceTransformer(
  File "/root/autodl-tmp/aiops24-RAG-demo/demo/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 191, in __init__
    modules = self._load_sbert_model(
  File "/root/autodl-tmp/aiops24-RAG-demo/demo/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 1233, in _load_sbert_model
    module = Transformer(model_name_or_path, cache_dir=cache_folder, **kwargs)
  File "/root/autodl-tmp/aiops24-RAG-demo/demo/.venv/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 36, in __init__
    self._load_model(model_name_or_path, config, cache_dir, **model_args)
  File "/root/autodl-tmp/aiops24-RAG-demo/demo/.venv/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 65, in _load_model
    self.auto_model = AutoModel.from_pretrained(
  File "/root/autodl-tmp/aiops24-RAG-demo/demo/.venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/root/autodl-tmp/aiops24-RAG-demo/demo/.venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3310, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### 复现步骤

安装依赖后在python main.py时出现HeaderTooLarge报错

### 代码分支

glm

### 运行环境

本地环境

**Comment by issaccv** [comment]
请检查git lfs是否启用，未启用则导致模型文件为空，从而导致加载错误
