### ISSUE TITLE
[BUG] ubuntu下运行 main.py 报错（已成功运行 run.sh，并pip了 requirements.txt）

### ISSUE THREAD

**Issue by yiouyou** [issaccv/aiops24-RAG-demo#9]
### 检查之前的issues

- [X] 我已经检查过之前的issues，没有我遇到的问题

### 描述Bug

运行 main.py 时，报错：
```
Traceback (most recent call last):
  File "/home/songz/aiops24-RAG-demo/demo/main+.py", line 71, in <module>
    asyncio.run(main())
  File "/home/songz/miniconda3/envs/ccf/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/ccf/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/ccf/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/songz/aiops24-RAG-demo/demo/main+.py", line 22, in main
    embeding = HuggingFaceEmbedding(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/ccf/lib/python3.11/site-packages/llama_index/embeddings/huggingface/base.py", line 86, in __init__
    self._model = SentenceTransformer(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/ccf/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 191, in __init__
    modules = self._load_sbert_model(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/ccf/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 1233, in _load_sbert_model
    module = Transformer(model_name_or_path, cache_dir=cache_folder, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/ccf/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py", line 36, in __init__
    self._load_model(model_name_or_path, config, cache_dir, **model_args)
  File "/home/songz/miniconda3/envs/ccf/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py", line 65, in _load_model
    self.auto_model = AutoModel.from_pretrained(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/ccf/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/ccf/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3310, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

### 复现步骤

1. pip requirements.txt
2. bash run.sh

### 代码分支

main

### 运行环境

本地环境

**Comment by issaccv** [comment]
dupe #5
